import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import "./ai-description.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { CompareProvider } from "@/contexts/CompareContext";
import { ProductNavigationProvider } from "@/contexts/ProductNavigationContext";
import { BrandProvider } from "@/contexts/BrandContext";
import { AuthProvider } from "@/contexts/AuthContext";
import CompareBar from "@/components/CompareBar";
import LoadingBar from "@/components/LoadingBar";
import SlideCartPanel from "@/components/SlideCartPanel";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

async function getEnabledLanguages(): Promise<string[]> {
  try {
    const backendUrl = process.env.NEXT_PUBLIC_API_URL || 'https://shop.didieffeb2b.com';
    const response = await fetch(`${backendUrl}/admin/data/translation-settings.json`, {
      cache: 'no-store', // Always get fresh data
    });

    if (!response.ok) {
      throw new Error('Failed to fetch translation settings');
    }

    const settings = await response.json();
    const languages = settings.languages || ['it'];

    // Ensure 'it' is always included as base language
    if (!languages.includes('it')) {
      languages.unshift('it');
    }

    return languages;
  } catch (error) {
    console.error('Error fetching enabled languages, using defaults:', error);
    // Fallback to 6 original languages if fetch fails
    return ['it', 'en', 'de', 'fr', 'es', 'pt'];
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const enabledLanguages = await getEnabledLanguages();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <LoadingBar />
        </Suspense>
        <Toaster position="top-right" richColors closeButton />
        <AuthProvider>
          <BrandProvider>
            <LanguageProvider initialLang="it" availableLanguages={enabledLanguages}>
              <ProductNavigationProvider>
                <CompareProvider>
                  {children}
                  <CompareBar />
                  <SlideCartPanel />
                </CompareProvider>
              </ProductNavigationProvider>
            </LanguageProvider>
          </BrandProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
