import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import "./ai-description.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { CompareProvider } from "@/contexts/CompareContext";
import { ProductNavigationProvider } from "@/contexts/ProductNavigationContext";
import { BrandProvider } from "@/contexts/BrandContext";
import CompareBar from "@/components/CompareBar";
import LoadingBar from "@/components/LoadingBar";
import SlideCartPanel from "@/components/SlideCartPanel";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <LoadingBar />
        </Suspense>
        <Toaster position="top-right" richColors closeButton />
        <BrandProvider>
          <LanguageProvider initialLang="it" availableLanguages={['it', 'en', 'de', 'fr', 'es', 'pt']}>
            <ProductNavigationProvider>
              <CompareProvider>
                {children}
                <CompareBar />
                <SlideCartPanel />
              </CompareProvider>
            </ProductNavigationProvider>
          </LanguageProvider>
        </BrandProvider>
      </body>
    </html>
  );
}
